In [1]:
!pip3 install pandas

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (0.25.3)
Requirement already satisfied: numpy>=1.13.3 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from pandas) (1.17.3)
Requirement already satisfied: python-dateutil>=2.6.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from pandas) (2.8.0)
Requirement already satisfied: pytz>=2017.2 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from pandas) (2019.3)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from python-dateutil>=2.6.1->pandas) (1.12.0)
WARNING: You are using pip version 20.0.2; however, version 21.2.4 is available.
You should consider upgrading via the '/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -m pip install --upgrade pip' command.

In [2]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [3]:
import pandas as pd
import numpy as np
np.set_printoptions(precision = 2, suppress=True)

df = pd.read_csv('COMPILE.csv')
print(df)

from sklearn.decomposition import PCA

P= PCA()
P.fit(df)
transformed = P.transform(df)
print(transformed)

from matplotlib import pyplot as plt
plt.scatter(transformed[:,0], transformed[:,1])
plt.show()

       verse     eng      cym        deu     fin    hat          hau  \
0   40012040      in       yn         in    -ssa    NaN        cikin
1   40018020      in       yn      unter  -llaan    NaN     tsakiyar
2   40024040      in       yn        auf    -lla    NaN            a
3   40026006      in       yn         in    -ssa     --            a
4   40027038      on       ar        zur    -lle    sou            a
5   40027061    near       --  gegenüber   -aata     --            a
6   41001004      in       yn         in    -ssa    NaN            a
7   41001019      in       yn         in    -ssa    NaN        cikin
8   41006047      on       ar        auf    -lla    NaN     tsakiyar
9   41006047      in      NaN        auf      --     --            a
10  41009033      in      NaN         in      --     --           --
11  41013008      in     mewn         --    -lla    NaN            a
12  41013015      on       ar        auf    -lla    sou          kan
13  41013016      in       yn        auf    -lla    NaN           --
14  41013029      at       yn   nahe vor    -lla    NaN            a
15  41014003      in       yn         in    -ssa     --            a
16  41014066      in       yn         in    -ssa    NaN            a
17  41015027      on       ar        zur    -lle    sou            a
18  42002008      in       yn         in    -lla    NaN            a
19  42003009      at     wrth         an    -lle     --            a
20  42014002      in       --        vor     NaN     --           --
21  42015025      in       yn        auf    -lla    NaN           --
22  42017031      on       ar        auf    -lla    sou        a kan
23  42017034      in       --        auf    -lla    sou            a
24  42018002      in     mewn         in    -ssa    NaN            a
25  42020037    near       --         --      --     --           --
26  42021011      in     mewn         --    -lle     --            a
27  42022021      at       ar        auf      --  bò la           --
28  42023025      in       --         in      --    NaN            a
29  43001026      in       yn         --      --    NaN    a cikinku
30  43002023      at       yn         an    -ssa    NaN           --
31  43005002      by     wrth         an    -lla  bò la           --
32  43011031      om       yn         in    -ssa    NaN      a cikin
33  43014002      om       --         in    -ssa    NaN            a
34  43019041      at       yn         an    -ssa    sou            a
35  44008008      om       yn         in      --    NaN       ciki a
36  44008009      om       yn         in    -ssa     --           --
37  44010006      by     wrth         an    -lla  bò la      a bakin
38  44011005      in       yn         in    -ssa    NaN          NaN
39  44014013      in       --        vor    -lla    NaN            a
40  44020008      in       yn         in    -ssa    NaN            a
41  44021021   among    ymysg      unter    -ssa    NaN      a cikin
42  46010001   under      dan      unter      --     --  a karkashin
43  51004015      in       yn         in  -ssaan     --            a
44  55002020      in     mewn         in    -ssa    NaN           --
45  58008004      on       ar        auf    -lla    sou           --
46  58011029      on       ar         --      --    sou           --
47  58013003      in       yn         --    -ssa    NaN            a
48  61001018      on       ar        auf    -lla    sou        a kan
49  66001013      in       yn         in    -lla    NaN   a tsakiyar
50  66004006  before       --         in    -lla     la       kewaye
51  66004006  around       yn        vor    -ssa     la           --
52  66007015  before  o flaen        vor    -ssa     la      a gaban
53  66007017      in       yn         --    -ssa    NaN   a tsakiyar
54  66019012      on       ar        auf  -ssaan    sou           --
55  66020008      in       yn         an      --     --           --
56  66022002      on       ar        auf    -lla    NaN           --

           hin                 jav        pol          tur            yor
0           mẽ                 ing          w        -inda           ninu
1           mẽ                 ing     pośród  arasindayim        li ãrin
2           mẽ                 ing         na          -da             li
3           mẽ                 ing          w          -da             ni
4          par                 ing          z        -inda             li
5   ke samhane                 ing  naprzeciw        -inda         dojukọ
6           mẽ                 ing         na          -da             ni
7          par                 ing          w          -da           ninu
8           mẽ                 ing  na środku          -da             ni
9          par                 ing         na           --          larin
10          --                 ing          w           --           ninu
11          --                 ing          w           --             ni
12         par                 ing         na          -da           lori
13          mẽ                 ing         na          -da             li
14         par                 ing          u  -indir, -da          lẹhin
15         NaN                 ing          w          -da             ni
16          mẽ                 ing         na          -da  ni isalẹ ãfin
17         par                 ing          z        -inda             li
18          mẽ                 ing          w          -da             ni
19           p                 ing         --           --             --
20  ke samhane                 ing      przed        -inda            NaN
21          mẽ                 ing         na          -da             li
22         par                 ing         na          -da           lori
23         par                  --         na           --           lori
24          mẽ                 ing          w           --             ni
25          --                  --         --           --             --
26         NaN                 ing         --           --             --
27         par                 ing         --          -da           lori
28          mẽ                 ing         --           --           sinu
29          mẽ                 ing     pośród     aranizda          larin
30          mẽ                 ing          w          -da             ni
31      ke pas           sacedhaké       przy      yaninda           leti
32          mẽ                 ing          w          -da           ninu
33          mẽ                 ing          w          -da           ninu
34         oar           sacedhaké          w          -da            NaN
35          mẽ                 ing          w          -da             ni
36          mẽ                 ing          w          -da             ni
37   ke kinare         ing pinngir       przy        -inda           leti
38          mẽ                 ing          w        -inda             ni
39  ke samhane           ing jaban   z przodu           --         niwaju
40          mẽ                 ing          w          -da             ni
41          --     ing satengahing         --     arasinda          lãrin
42   ke neeche                 ing        pod        -inda           labẹ
43          --                 ing          w          -da             ni
44          mẽ       ing sajroning          w          -da           ninu
45         par                 ing         na        -inda             li
46         par                  --         --           --            NaN
47          --                  --         --          -da            NaN
48         par                 ing         na        -inda           lori
49          mẽ  ing tengah tengahé          w           --          lãrin
50          mẽ       ing santegahé          w        -inda        li arin
51  ke samhane         ing ngarepé      przed        -inda         niwaju
52  ke samhane        ing ngarsané        NaN        -inda         niwaju
53          mẽ                  --          w        -inda        li arin
54         par                  --         na        -inda             li
55          --                 ing         na           --             ni
56         par  ing sakiwa tengené        NaN        -inda             --

ValueError: could not convert string to float: 'in'

In [4]:
df.head()

,verse,eng,cym,deu,fin,hat,hau,hin,jav,pol,tur,yor
0,40012040,in,yn,in,-ssa,NaN,cikin,mẽ,ing,w,-inda,ninu
1,40018020,in,yn,unter,-llaan,NaN,tsakiyar,mẽ,ing,pośród,arasindayim,li ãrin
2,40024040,in,yn,auf,-lla,NaN,a,mẽ,ing,na,-da,li
3,40026006,in,yn,in,-ssa,--,a,mẽ,ing,w,-da,ni
4,40027038,on,ar,zur,-lle,sou,a,par,ing,z,-inda,li

In [5]:
df[['line']].head()

KeyError: "None of [Index(['line'], dtype='object')] are in the [columns]"

In [6]:
import pandas as pd
import numpy as np
np.set_printoptions(precision = 2, suppress=True)

en_df = pd.read_csv('en_tag.csv')
print(df)

from sklearn.decomposition import PCA

P= PCA()
P.fit(df)
transformed = P.transform(df)
print(transformed)

from matplotlib import pyplot as plt
plt.scatter(transformed[:,0], transformed[:,1])
plt.show()

     line  en_ppf_u  en_ppf_e  en_spt  en_cpr  en_prs  de_ppf  de_spt  \
0     PRS         0         0       0       0       1       0       0
1   PPF_U         1         0       0       0       0       0       0
2   PPF_E         0         1       0       0       0       1       0
3     SPT         0         0       1       0       0       1       0
4     SPT         0         0       1       0       0       1       0
..    ...       ...       ...     ...     ...     ...     ...     ...
74    SPT         0         0       1       0       0       0       0
75  PPF_E         0         1       0       0       0       1       0
76    PRS         0         0       0       0       1       0       0
77    PRS         0         0       0       0       1       0       0
78    PRS         0         0       0       0       1       0       0

    de_spt_b  de_prs  ...  ka_fsj  ka_con  ka_opt  ka_prs  zh_non  zh_le  \
0          0       1  ...       0       0       0       1       0      0
1          0       1  ...       0       0       0       0       1      0
2          0       0  ...       0       0       0       0       0      0
3          0       0  ...       0       0       0       0       0      0
4          0       0  ...       0       0       0       0       1      0
..       ...     ...  ...     ...     ...     ...     ...     ...    ...
74         1       0  ...       0       0       0       0       1      0
75         0       0  ...       0       0       0       0       0      0
76         0       1  ...       0       0       0       1       1      0
77         0       1  ...       0       0       0       1       0      1
78         0       1  ...       0       0       0       1       0      1

    zh_guo  zh_you  zh_shi  zh_oth
0        1       0       0       0
1        0       0       0       0
2        1       0       0       0
3        1       0       0       0
4        0       0       0       0
..     ...     ...     ...     ...
74       0       0       0       0
75       0       0       0       1
76       0       0       0       0
77       0       0       0       0
78       0       0       0       0

[79 rows x 31 columns]

ValueError: could not convert string to float: 'PRS'

,line,en_ppf_u,en_ppf_e,en_spt,en_cpr,en_prs,en_ppg,de_ppf,de_spt,de_spt_b,...,ka_con,ka_opt,ka_prs,zh_non,zh_le,zh_guo,zh_you,zh_shi,zh_oth,line
0,1014_001,0,0,0,0,1,0,0,0,0,...,0,0,1,0,0,1,0,0,0,1014_001
1,1014_019,1,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1014_019
2,1014_031,0,1,0,0,0,0,1,0,0,...,0,0,0,0,0,1,0,0,0,1014_031
3,1014_032,0,0,1,0,0,0,1,0,0,...,0,0,0,0,0,1,0,0,0,1014_032
4,1014_033,0,0,1,0,0,0,1,0,0,...,0,0,0,1,0,0,0,0,0,1014_033